/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasilaundry;
import java.awt.Color;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;


/**
 *
 * @author KRISNA
 */
public class MenuUtama extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuUtama.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public MenuUtama() {
    initComponents();
        Color biruIsi = new Color(0, 51, 102);      
    Color biruHeader = new Color(0, 34, 68);  
    tabelTransaksi.setBackground(biruIsi);
    tabelTransaksi.setForeground(Color.WHITE);
    tabelTransaksi.setSelectionBackground(new Color(0, 102, 204));
    tabelTransaksi.setSelectionForeground(Color.WHITE);
    tabelTransaksi.setFillsViewportHeight(true);
    jScrollPane1.getViewport().setBackground(biruIsi);
    DefaultTableCellRenderer header = new DefaultTableCellRenderer();
    header.setBackground(biruHeader);
    header.setForeground(Color.WHITE);
    header.setHorizontalAlignment(DefaultTableCellRenderer.CENTER);
    header.setOpaque(true);
    tabelTransaksi.setShowGrid(true);
    tabelTransaksi.setGridColor(new Color(180, 180, 180));
    tabelTransaksi.setRowMargin(1);
    tabelTransaksi.getTableHeader().setDefaultRenderer(header);
    tabelTransaksi.setModel(Transaksi.getData());

    cmbStatus.removeAllItems();
    cmbStatus.addItem("proses");
    cmbStatus.addItem("selesai");
    cmbStatus.addItem("diambil");
}
    private void hitungTotal() {
    try {
        double b = Double.parseDouble(txtBerat.getText());
        double h = Double.parseDouble(txtHargaPerKg.getText());
        txtTotal.setText(String.valueOf((int)(b * h)));
    } catch (Exception e) {
        txtTotal.setText("");
    }
}

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtBerat = new javax.swing.JTextField();
        txtHargaPerKg = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelTransaksi = new javax.swing.JTable();
        cmbStatus = new javax.swing.JComboBox<>();
        bginput = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        bg = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Berat");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Harga /kg");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Total Bayar");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, -1, 50));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Status");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, -1, -1));

        txtNama.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });
        jPanel1.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 184, 51));

        txtBerat.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        txtBerat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBeratActionPerformed(evt);
            }
        });
        txtBerat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBeratKeyReleased(evt);
            }
        });
        jPanel1.add(txtBerat, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 184, 54));

        txtHargaPerKg.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        txtHargaPerKg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaPerKgActionPerformed(evt);
            }
        });
        txtHargaPerKg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtHargaPerKgKeyReleased(evt);
            }
        });
        jPanel1.add(txtHargaPerKg, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 184, 51));

        txtTotal.setEditable(false);
        txtTotal.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        jPanel1.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, 184, 49));

        btnSimpan.setBackground(new java.awt.Color(51, 204, 0));
        btnSimpan.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel1.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 580, 190, 66));

        btnTambah.setBackground(new java.awt.Color(51, 153, 255));
        btnTambah.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        jPanel1.add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 580, 190, 65));

        btnUbah.setBackground(new java.awt.Color(255, 153, 0));
        btnUbah.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnUbah.setForeground(new java.awt.Color(255, 255, 255));
        btnUbah.setText("Edit");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });
        jPanel1.add(btnUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 670, 190, 63));

        btnHapus.setBackground(new java.awt.Color(255, 51, 51));
        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel1.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 670, 190, 68));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Nama: ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 35)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Data Laundry");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 150, -1, -1));

        tabelTransaksi.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tabelTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelTransaksi.setRowHeight(30);
        tabelTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelTransaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelTransaksi);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 220, 620, 420));

        cmbStatus.setBackground(new java.awt.Color(255, 255, 255));
        cmbStatus.setForeground(new java.awt.Color(0, 0, 0));
        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStatusActionPerformed(evt);
            }
        });
        jPanel1.add(cmbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 500, 184, 41));

        bginput.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasilaundry/input.png"))); // NOI18N
        jPanel1.add(bginput, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 540, 660));

        jButton1.setText("Keluar");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 660, 160, 50));

        jButton2.setText("Pembayaran");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 660, 160, 50));

        jButton3.setText("Data Pelanggan");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 660, 160, 50));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasilaundry/bg.png"))); // NOI18N
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1520, 830));

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBeratKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBeratKeyReleased
        // TODO add your handling code here:
        hitungTotal();
    }//GEN-LAST:event_txtBeratKeyReleased

    private void txtHargaPerKgKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHargaPerKgKeyReleased
        // TODO add your handling code here:
        hitungTotal();
    }//GEN-LAST:event_txtHargaPerKgKeyReleased

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        txtNama.setText("");
        txtBerat.setText("");
        txtHargaPerKg.setText("");
        txtTotal.setText("");
        txtNama.requestFocus();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
          String nama = txtNama.getText();
    double berat = Double.parseDouble(txtBerat.getText());
    int hargaPerKg = Integer.parseInt(txtHargaPerKg.getText()); // baru
    int total = Integer.parseInt(txtTotal.getText());
    String status = cmbStatus.getSelectedItem().toString();

    int idCustomer = Customer.insert(nama, "-");

    Transaksi.insert(idCustomer, berat, hargaPerKg, total, status);

    tabelTransaksi.setModel(Transaksi.getData());

    txtNama.setText("");
    txtBerat.setText("");
    txtHargaPerKg.setText("");
    txtTotal.setText("0");
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
            int row = tabelTransaksi.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Pilih data transaksi terlebih dahulu!");
        return;
    }

    int idTransaksi = Integer.parseInt(tabelTransaksi.getValueAt(row, 0).toString());
    int idCustomer = Integer.parseInt(tabelTransaksi.getValueAt(row, 1).toString());
    String nama = txtNama.getText();
    double berat = Double.parseDouble(txtBerat.getText());
    int hargaPerKg = Integer.parseInt(txtHargaPerKg.getText()); // baru
    int total = Integer.parseInt(txtTotal.getText());
    String status = cmbStatus.getSelectedItem().toString();

    Customer.updateNama(idCustomer, nama);
    Transaksi.update(idTransaksi, berat, hargaPerKg, total, status); // update dengan hargaPerKg

    tabelTransaksi.setModel(Transaksi.getData());

    txtNama.setText("");
    txtBerat.setText("");
    txtHargaPerKg.setText("");
    txtTotal.setText("0");

    JOptionPane.showMessageDialog(this, "Data berhasil diupdate!");
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        
    int row = tabelTransaksi.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Pilih data dulu");
        return;
    }

    int opsi = JOptionPane.showConfirmDialog(
        this,
        "Yakin ingin menghapus transaksi ini?",
        "Konfirmasi",
        JOptionPane.YES_NO_OPTION
    );

    if (opsi == JOptionPane.YES_OPTION) {
        int idTransaksi = Integer.parseInt(
            tabelTransaksi.getValueAt(row, 0).toString()
        );

        Transaksi.delete(idTransaksi);
        tabelTransaksi.setModel(Transaksi.getData());
    }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void cmbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbStatusActionPerformed

    private void tabelTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelTransaksiMouseClicked
        // TODO add your handling code here:
 int row = tabelTransaksi.getSelectedRow();
    txtNama.setText(tabelTransaksi.getValueAt(row, 2).toString());
    txtBerat.setText(tabelTransaksi.getValueAt(row, 4).toString());
     txtHargaPerKg.setText(tabelTransaksi.getValueAt(row, 5).toString());
    txtTotal.setText(tabelTransaksi.getValueAt(row, 6).toString());
    cmbStatus.setSelectedItem(tabelTransaksi.getValueAt(row, 7).toString());

cmbStatus.setSelectedItem(
    tabelTransaksi.getValueAt(row, 7).toString()
);
    }//GEN-LAST:event_tabelTransaksiMouseClicked

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void txtHargaPerKgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaPerKgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaPerKgActionPerformed

    private void txtBeratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBeratActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBeratActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(() -> {
        new MenuUtama().setVisible(true);
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel bginput;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelTransaksi;
    private javax.swing.JTextField txtBerat;
    private javax.swing.JTextField txtHargaPerKg;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
